modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
An addon for Synaxis that extends its capabilities within Create and Create Aeronautics ecosystems.
'''

[[mixins]]
config="mixins.${mod_id}.json"

# === Required Dependencies ===

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="synaxis"
type="required"
versionRange="[1.1.6,)"
ordering="AFTER"
side="BOTH"

# === Optional Dependencies ===

[[dependencies.${mod_id}]]
modId="aeronautics"
type="optional"
versionRange="[1.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simulated"
type="optional"
versionRange="[1.2.1,)"
ordering="AFTER"
side="BOTH"
